# Generated by Django 4.1 on 2022-09-01 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourn_name', models.CharField(max_length=100, unique=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tourn_type', models.CharField(choices=[('league', 'League'), ('knockout_h2h', 'Knockout_h2h'), ('league_h2h', 'League_h2h')], default='league', max_length=20)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('rtgs', 'RTGS'), ('rands', 'RANDS')], max_length=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('max_teams', models.IntegerField()),
                ('slug', models.SlugField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('squad', models.JSONField()),
                ('team', models.JSONField()),
                ('team_bench', models.JSONField(default={'player': 'ghost'})),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('terms_and_conditions', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
