# Generated by Django 4.1 on 2022-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tournament_is_active_tournament_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
