# Generated by Django 4.1 on 2022-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='squad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_bench',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
