# Generated by Django 4.1 on 2022-09-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_team_squad_alter_team_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='squad',
            field=models.JSONField(blank=True, default={'player': 'rango'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.JSONField(blank=True, default={'player': 'rango'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_bench',
            field=models.JSONField(blank=True, default={'player': 'rango'}, max_length=100),
        ),
    ]
