# Generated by Django 4.1 on 2022-09-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_balance_alter_team_squad_alter_team_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deadline_time', models.DateTimeField()),
            ],
        ),
    ]
