# Generated by Django 4.1 on 2022-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gameweeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_teams',
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_teams',
            field=models.IntegerField(default=3),
        ),
    ]
