# Generated by Django 4.1 on 2022-09-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_tournament_max_teams_tournament_min_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_of_teams',
            field=models.IntegerField(default=1),
        ),
    ]
