# Generated by Django 4.1 on 2022-09-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tournament_number_of_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tourn_closed',
            field=models.BooleanField(default=False),
        ),
    ]
